# Generated by Django 3.2.25 on 2026-07-17 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('model', models.TextField()),
                ('detail', models.TextField()),
                ('instance_id', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'timestamp'], name='users_recor_user_id_f15ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['timestamp'], name='users_recor_timesta_af2ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['user'], name='users_assig_user_id_39f9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['room'], name='users_assig_room_id_4e03c5_idx'),
        ),
    ]
