# Generated by Django 3.2.25 on 2026-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['user'], name='users_assig_user_id_39f9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='assign',
            index=models.Index(fields=['room'], name='users_assig_room_id_4e03c5_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user', 'timestamp'], name='users_recor_user_id_f15ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['timestamp'], name='users_recor_timesta_af2ad0_idx'),
        ),
    ]
