# Generated by Django 4.2.4 on 2023-11-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='action',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='model',
            field=models.TextField(),
        ),
    ]
