# Generated by Django 4.2.4 on 2023-11-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_record_action_alter_record_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
