# Generated by Django 4.2.4 on 2023-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_sub_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_environment',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
