# Generated by Django 4.2.4 on 2023-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_property_name_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(upload_to="'room_photos/'"),
        ),
    ]
