# Generated by Django 3.2.25 on 2026-07-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20260727_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id']},
        ),
    ]
