# Generated by Django 4.2.4 on 2023-11-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_property_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Environment',
            new_name='Sub_Room',
        ),
    ]
