# Generated by Django 4.2.4 on 2023-10-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='payment_plan',
        ),
    ]
