# Generated by Django 3.2.25 on 2026-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['rental'], name='financials__rental__671c00_idx'),
        ),
        migrations.AddIndex(
            model_name='warranty_movement',
            index=models.Index(fields=['rental'], name='financials__rental__64ad0b_idx'),
        ),
    ]
