# Generated by Django 4.2.4 on 2023-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_warranty_movement_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warranty_movement',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warranty_movement',
            name='voucher_number',
            field=models.CharField(max_length=255),
        ),
    ]
