# Generated by Django 4.2.4 on 2023-11-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nup',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer_type',
            name='is_police',
            field=models.BooleanField(default=False),
        ),
    ]
