# Generated by Django 4.2.4 on 2023-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='institution_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
