# Generated by Django 3.2.25 on 2026-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_contact_nup_customer_type_is_police'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['customer', 'is_active'], name='customers_c_custome_f94c85_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_c_custome_1bdb7e_idx'),
        ),
    ]
