# Generated by Django 3.2.25 on 2026-07-17 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.rental')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='RateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer_type')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.rate')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement')),
            ],
        ),
        migrations.AddIndex(
            model_name='requirement_delivered',
            index=models.Index(fields=['rental'], name='requirement_rental__a26502_idx'),
        ),
        migrations.AddIndex(
            model_name='raterequirement',
            index=models.Index(fields=['rate', 'customer_type', 'is_active'], name='requirement_rate_id_fac4f2_idx'),
        ),
    ]
