# Generated by Django 3.2.25 on 2026-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='raterequirement',
            index=models.Index(fields=['rate', 'customer_type', 'is_active'], name='requirement_rate_id_fac4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='requirement_delivered',
            index=models.Index(fields=['rental'], name='requirement_rental__a26502_idx'),
        ),
    ]
