# Generated by Django 4.2.4 on 2023-10-17 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_rental_is_plan_rental_state_delete_rental_state'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement_Delivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.rental')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirement')),
            ],
        ),
        migrations.DeleteModel(
            name='PlanRequirement',
        ),
    ]
