# Generated by Django 3.2.25 on 2026-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='roles_userr_user_id_3c847e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='roles_userr_role_id_81e387_idx'),
        ),
    ]
