# Generated by Django 4.2.4 on 2023-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='warranty_return_request',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='warranty_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
