# Generated by Django 4.2.4 on 2023-10-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leases.state'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rental_State',
        ),
    ]
