# Generated by Django 3.2.25 on 2024-09-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0002_rental_warranty_return_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancel_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
