# Generated by Django 4.2.4 on 2023-10-16 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('leases', '0002_rental_is_plan_rental_state_delete_rental_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='initial_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='selected_product',
            name='product_price',
            field=models.FloatField(null=True),
        ),
    ]
