# Generated by Django 4.2.4 on 2023-10-20 14:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_rental_initial_total_rental_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='year',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None),
        ),
    ]
