# Generated by Django 3.2.25 on 2026-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_rental_cancel_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='additional_hour_applied',
            index=models.Index(fields=['selected_product'], name='leases_addi_selecte_4ecb31_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['state', 'customer'], name='leases_rent_state_i_acd8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['customer', 'state'], name='leases_rent_custome_2c9a42_idx'),
        ),
        migrations.AddIndex(
            model_name='selected_product',
            index=models.Index(fields=['rental', 'product'], name='leases_sele_rental__741378_idx'),
        ),
    ]
