# Generated by Django 4.2.4 on 2023-10-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_rental_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_plan',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='year',
        ),
    ]
