# Generated by Django 4.2.4 on 2023-11-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_remove_rental_is_plan_remove_rental_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Hour_Applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('voucher_number', models.CharField()),
                ('total', models.FloatField()),
                ('description', models.CharField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leases.selected_product')),
            ],
        ),
    ]
