# Generated by Django 4.2.4 on 2023-11-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_additional_hour_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='contract_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
