# Generated by Django 4.2.4 on 2023-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_rental_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_hour_applied',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='additional_hour_applied',
            name='voucher_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selected_product',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
