# Generated by Django 3.2.25 on 2026-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
