# Generated by Django 4.2.4 on 2023-10-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_sub_environment_quantity'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_Additional_Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.FloatField()),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hourRange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hourrange')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
        ),
    ]
