# Generated by Django 4.2.4 on 2023-11-28 21:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_price_additional_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='day',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
