# Generated by Django 3.2.25 on 2026-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20260707_1404'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'is_active'], name='products_pr_product_d3c839_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rate', 'room', 'is_deleted'], name='products_pr_rate_id_0b420e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['room', 'is_deleted'], name='products_pr_room_id_d92277_idx'),
        ),
    ]
